### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by tmpm697** [AlexanderThaller/hstdb#14]
I find this repo different from histdb as it also does not use `real` sqlite db as its inspirer.

So I suggest changing its name to like `hstdb`

and can you make it to official archlinux repo? as I'm building images that depends on it.

**Comment by AlexanderThaller** [comment]
We can think about a name change for sure. Maybe we can also just use something completely different like https://github.com/ellie/atuin did. I'm open to suggestions.

I created an aur https://aur.archlinux.org/packages/histdb-rs/ for this I have never brought an aur into the official repository but I can certainly try.

You can also use https://github.com/AlexanderThaller/custom_archlinux_thaller_ws (https://custom-archlinux.thaller.ws/) if you trust what I did there which will provide prebuilt packages but having it in the official repo would be very nice.

**Comment by tmpm697** [comment]
Hi, I find it weird with `custom_archlinux_thaller_ws`, afai understand, you `build` some packages inside docker -- this is I believe not archlinux way but still work. I'd rather use `mkosi` and `systemd-nspawn` for building packages/apps.

what is `docker run <..> build` in `https://github.com/AlexanderThaller/custom_archlinux_thaller_ws/blob/f5dfd04c575097aa66c6755c1673b96e391823aa/Makefile#L29`?

Yes, we can go totally different name. `-rs` part seems problematic. I still suggest `hstdb` for short. 3 chars in name is too short but 5 is perfectly fine imo.

**Comment by AlexanderThaller** [comment]
> Hi, I find it weird with `custom_archlinux_thaller_ws`, afai understand, you `build` some packages inside docker -- this is I believe not archlinux way but still work. I'd rather use `mkosi` and `systemd-nspawn` for building packages/apps.
> 
> what is `docker run <..> build` in `https://github.com/AlexanderThaller/custom_archlinux_thaller_ws/blob/f5dfd04c575097aa66c6755c1673b96e391823aa/Makefile#L29`?
> 
> Yes, we can go totally different name. `-rs` part seems problematic. I still suggest `hstdb` for short. 3 chars in name is too short but 5 is perfectly fine imo.

Yeah the custom stuff is just for me mostly. I think hstdb is a nice name will rename it and see if i can get it into the community repo.

**Comment by tmpm697** [comment]
Idk just a name and I give a suggestion as -rs trigger me a lot when typing the command. 

I think we can close it. And please choose whatever name you want. If it's too long or complex I'll fork, you know 😂🌚👴

**Comment by AlexanderThaller** [comment]
Renamed to `hstdb`.
